play/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^play_app/', include('play_app.urls'))
]

play_app/urls.py
from django.conf.urls import url
from play_app import views

app_name = "play_app"

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^searchResult/', views.search_result_view, name='search_result'),
	url(r'^login/', views.login_view, name='login'),
	url(r'^create_playlist_ajax/$', views.create_playlist_ajax, name='create_playlist_ajax'),
]

play_app/models.py
from django.db import models

# Create your models here.

play_app/forms.py
from django import forms
#built in validators
from django.core import validators

class SearchArtistForm(forms.Form):
	artist = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Search for an artist', 'id':'artist-js'}))
	botcatcher = forms.CharField(required=False,
								widget=forms.HiddenInput,
								validators=[validators.MaxLengthValidator(0)])

class MakePlaylistForm(forms.Form):
	title = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Playlist Title', 'id':'playlistTitle-js'}))

	botcatcher = forms.CharField(required=False,
								widget=forms.HiddenInput,
								validators=[validators.MaxLengthValidator(0)])

play_app/views.py
# Django imports
from django.contrib.auth import logout
from django.shortcuts import render
from django.http import JsonResponse
# This project imports
from . import forms
from . import objects
# Spotipy imports
import spotipy
from spotipy.oauth2 import SpotifyClientCredentials
# Misc. imports
import requests
import json

SETLIST_FM_API_KEY = 'b0bf96c4-6af5-4ac0-ae87-1b3d8e6cd9cb'
SPOTIFY_CLIENT_ID = 'bb7dcf3b9cf841939c48ef54843ef28a'
SPOTIFY_CLIENT_SECRET = '27f9dd07f1d44be8b12fea7d297be7f6'


def index(request):
	'''
		Inserts a form into the index page
	'''
	form = forms.SearchArtistForm()
	context = {'form': form}
	return render(request, 'play_app/index.html', context)


def searchTracksFromArtist(artist, limit, offset, array):
	'''
		Requests all songs from an artist and adds them to a dictionary
		Calls itself if not all songs have been visited
	'''
	client_credentials_manager = SpotifyClientCredentials(SPOTIFY_CLIENT_ID, SPOTIFY_CLIENT_SECRET)
	sp = spotipy.Spotify(client_credentials_manager=client_credentials_manager)
	results = sp.search(q=artist, limit=limit, offset=offset)

	for i in results['tracks']['items']:
		array[i['name'].lower()] = i['id']
	if(results['tracks']['total'] > limit*offset):
		offset += 50
		searchTracksFromArtist(artist, limit, offset, array)

def getAllSongsFromArtist(artist):
	'''
		Gets all songs from an artist using Spotiy's API
		returns a dictionary of those songs (key) with an ID (value)
		Works because Python is pass-by-object-reference
	'''
	array = {}
	searchTracksFromArtist(artist, 50, 0, array)
	return array

def getQueryFromSetlistFM(headers, context):
	'''
		Requests artist information from Setlist.FM
		Returns a json object for the artist
	'''
	artist_search_url   = 'https://api.setlist.fm/rest/1.0/search/artists?artistName={}&p=1&sort=sortName'
	artist_search_query = artist_search_url.format(context['artist'])
	r = requests.get(artist_search_query, headers=headers)
	return r.json()

def getSetlists(headers, context):
	'''
		Requests setlists for an artist from Setlist.FM
		Returns a json object for the setlists
	'''
	mbid = context['query']['artist'][0]['mbid']
	artist_setlist_url   = 'https://api.setlist.fm/rest/1.0/artist/{}/setlists?p=1'
	artist_setlist_query = artist_setlist_url.format(mbid)
	r = requests.get(artist_setlist_query, headers=headers)
	return r.json()

def getImageURL(context):
	'''
		Requests the image url from the Spotify API
		Returns that url
	'''
	client_credentials_manager = SpotifyClientCredentials(SPOTIFY_CLIENT_ID, SPOTIFY_CLIENT_SECRET)
	sp = spotipy.Spotify(client_credentials_manager=client_credentials_manager)
	results = sp.search(q='artist:' + context['artist'], limit=5, type='artist')
	#This is the structure of the Spotify API object to get an image url
	image_url = results['artists']['items'][0]['images'][0]['url']
	return image_url

### Searches for an artist with Setlist.fm's api
### Grabs that artist's 'mbid'
### Searches for an artist's recent setlists with Setlist.fm's api
### Store ~20 (1 page in the api) results in context
def search_result_view(request):
	'''
		Searches for an artist with Setlist.fm's api
		Creates artist & setlist objects that will later
		be displayed on the screen.
		Gets the image of the artist/band.
		Gets all of the songs from an artist/band available
		on Spotify so that the ones not available can be
		specified on the screen.

	'''
	print("SEARCH RESULT")
	context = {}
	if request.method == 'POST':
		form = forms.SearchArtistForm(request.POST)

		if form.is_valid():
			context['artist'] = form.cleaned_data['artist']
	else:
		return index(request)
	
	#SETLIST.FM -- search for artist
	headers = {
		'Accept': 'application/json',
		'x-api-key': SETLIST_FM_API_KEY
	}
	context['query'] = getQueryFromSetlistFM(headers, context)

	#SETLIST.FM -- get artist's setlists
	artist_list = []
	#possible that the user enters in an artist that can't be found
	#either due to typo or not existing
	try:
		for i in range(0, 20):
			artist_list.append(objects.Artist(context['query']['artist'][0], i))
	except KeyError:
		context['error_message'] = "'" + context['artist'] + "' cannot be found."
		return render(request, 'play_app/searchError.html', context)

	context['setlists'] = getSetlists(headers, context)

	i = 0
	for artist in artist_list:
		try:
			artist.setlist = objects.Setlist(context['setlists']['setlist'][i])
		except KeyError:
			context['error_message'] = "'" + context['artist'] + "' does not have any setlists."
			return render(request, 'play_app/searchError.html', context)
		i += 1
	context['artist_list'] = artist_list

	#SPOTIFY -- get image url for artist
	context['image_url'] = getImageURL(context)

	#Playlist form, maybe remove if JS/Ajax is used?
	playlist_form = forms.MakePlaylistForm()
	context['playlist_form'] = playlist_form

	#Get all songs from the artist
	context['all_songs'] = getAllSongsFromArtist(context['artist'])
	context['all_songs_json'] = json.dumps(context['all_songs'])

	return render(request, 'play_app/searchResult.html', context)

def login_view(request):
	'''
		Page for logging into Spotify.
	'''
	print("LOGGING IN")
	return render(request, 'play_app/login.html', {})

def create_playlist_ajax(request):
	'''
		Receives playlist data from searchResult.
		Creates a new playlist for the given user
		using the given details. Sends back the data
		dictionary.
	'''
	print("CREATING PLAYLIST")
	data = {}
	if request.method == 'GET':
		data['title'] = request.GET['title']
		data['songs'] = json.loads(request.GET['songs'])
		data['visibility'] = request.GET['visibility']
		data['access_token'] = request.GET['access_token']
		data['user_id'] = request.GET['user_id']
		data['all_songs'] = json.loads(request.GET['all_songs'])
		data['song_ids'] = []

	# Initialize spotipy object
	sp = spotipy.Spotify(auth=data['access_token'])
	sp.trace = False

	# Create a new playlist for the given user, title, and visibility
	playlists = sp.user_playlist_create(data['user_id'], data['title'], data['visibility']);
	data['playlist_id'] = playlists['id']

	# Retrieve all of the id's for the songs in this new playlist
	for song in data['songs']:
		data['song_ids'].append(data['all_songs'][song])

	# Add songs to the newly created playlist
	result = sp.user_playlist_add_tracks(data['user_id'], data['playlist_id'], data['song_ids'])
	return JsonResponse(data)

templates/play_app/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">

<head>
	<meta charset="UTF-8">
	<title>{% block title %}{% endblock %}</title>

	<link rel="stylesheet" href="{% static 'play_app\css\base.css' %}" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-alpha.3/css/materialize.min.css">
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	{% block stylesheets %}{% endblock %}

	<link rel="icon" href="{% static 'play_app/images/site_icon.png' %}">
</head>

<body>
	<nav class="teal accent-4 pin-nav">
		<div class="nav-wrapper">
			<a href="{% url 'play_app:index' %}" class="brand-logo left">𝓢𝓹𝓸𝓽𝓲𝓟𝓵𝓪𝔂</a>
			<ul class="right">
				<li class="home-li-js"><a href="{% url 'play_app:index' %}"><i class="material-icons left">home</i>Home</a></li>
				<li><a id="loginBtn-js" href="" onclick="loginSpotify()"><i class="material-icons left">account_box</i>Login</a></li>
			</ul>		
		</div>
	</nav>

	{% block body_block %}{% endblock %}
	
	<script src="{% static 'play_app/jquery-3.2.1.js' %}"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-alpha.3/js/materialize.min.js"></script>
	<script src="{% static 'play_app/js/base.js' %}"></script>
	{% block scripts %}{% endblock %}
</body>

</html>

templates/play_app/index.html
<!DOCTYPE html>
{% extends "play_app/base.html" %}
{% load staticfiles %}
	{% block title %}
		SpotiPlay
	{% endblock %}

	{% block stylesheets %}
		<link rel="stylesheet" href="{% static 'play_app/css/index.css' %}">
	{% endblock %}

	{% block body_block %}
		<div class="row"></div>
		<div class="row">
			<!-- FORM CARD -->
			<div class="col s12 m12 l6">
				<div class="card">
					<div class="card-image">
						<img src="{% static 'play_app/images/collage.jpg' %}">
					</div>
					<div class="card-content">
						<span class="card-title">Search for an artist:</span>
						<form id="searchForm-js" onsubmit="return validateSearch();" action="{% url 'play_app:search_result' %}" method="POST">
							{% csrf_token %}
							{{ form.artist }}
							<button class="teal accent-4 waves-effect waves-light btn" type="submit"> <i class="material-icons right">search</i>Search</button>
						</form>
					</div>
				</div>
			</div>

			<div class="col s12 m12 l4 offset-s0 offset-m0 offset-l1">
				<!-- ABOUT CARD -->
				<div class="row">
					<div class="col s12 m12 l12">
						<div class="card">
							<div class="card-content">
								<span class="card-title">About</span> <hr>
								<p>SpotiPlay is a personal project of mine. I have a passion for music and web development so putting them together seemed obvious! I go to concerts all the time and make playlists so that I go in prepared. With this application, you can save yourself hours of adding individual songs to a playlist for that upcoming concert, or you can relive a recent show by making a playlist out of that! To use:</p>
								<ol>
									<li>Log into your Spotify account with the Login button in the menu bar.</li>
									<li>Search for an artist.</li>
									<li>Choose a setlist.</li>
									<li>Name your playlist and choose whether it should be public or private</li>
									<li>Open up Spotify and enjoy!</li>
								</ol>
							</div>
						</div>
					</div>
				</div>

				<!-- FEEDBACK CARD -->
				<div class="row">
					<div class="col s12 m12 l12">
						<div class="card">
							<div class="card-content">
								<span class="card-title">Feedback</span> <hr>
								<p>Have feedback? I'd love to hear it! Whether there's a feature you think should be implemented, a bug, or just a compliment, it is all welcome. Send any feedback to: <span class="grey-text">churt.dev@gmail.com</span></p>
							</div>
						</div>
					</div>
				</div>

			</div>
		</div>

		<div class="footer teal darken-4">
			<p class="white-text">
				SpotiPlay created by 
				<a class="grey-text" href="https://github.com/topher235" target="_blank">Christopher Hurt</a>, powered by 
				<a class="grey-text" href="https://www.spotify.com" target="_blank">Spotify</a> and 
				<a class="grey-text" href="https://www.setlist.fm" target="_blank">Setlist.fm</a>
			</p>
			<p class="white-text">Enjoying SpotiPlay? Developers like myself are powered by <a class="grey-text" href="https://www.paypal.me/CHurt257" target="_blank">coffee</a></p>
        </div>
	{% endblock %}

	{% block scripts %}
		<script src="{% static 'play_app/js/index.js' %}"></script>
	{% endblock %}

templates/play_app/login.html
<!DOCTYPE html>
{% extends "play_app/base.html" %}

{% block body_block %}
	<h3 class="black-text">Success</h3>
{% endblock %}

{% block scripts %}
	<script>
		function parseHash(data) {
			return data.split("access_token=")[1].split("&")[0];
		}
		
		$('document').ready(function() {
			var spotifyAccessToken = parseHash(String(window.location.hash));
			console.log(spotifyAccessToken);
			localStorage.clear();
			localStorage.setItem('accessToken', spotifyAccessToken);
			localStorage.setItem('accessTokenDate', new Date());
			window.close();
		});
	</script>
{% endblock %}

templates/play_app/searchError.html
<!DOCTYPE html>
{% extends 'play_app/base.html' %}
{% load staticfiles %}

{% block body_block %}
	<div class="row">
		<div class="col s10 m10 l6 offset-s1 offset-m1 offset-l3">
			<div class="card">
				<div class="card-image">
					<img src="{% static 'play_app/images/headphones.jpg' %}" />
				</div>
				<div class="card-content">
					<span class="card-title black-text">Search error:</span>
					<h4>{{ error_message }}</h4>
					<button class="waves-effect waves-light btn-large" onclick="returnToHome()">Return</button>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

{% block scripts %}
	<script>
		function returnToHome() {
			window.location = "/play_app/";
		}
	</script>
{% endblock %}

templates/play_app/searchResult.html
<!DOCTYPE html>
{% extends 'play_app/base.html' %}
{% load staticfiles %}
	{% block title %}
		Search Results
	{% endblock %}

	{% block stylesheets %}
		<link rel="stylesheet" href="{% static 'play_app/css/searchResult.css' %}">
	{% endblock %}

	{% block body_block %}
		<div class="row">

			<!-- Artist name and artist image -->
			<div class="col s6 m6 pin-card">
				<div class="card large">
					<div class="card-image">
						<img src="{{ image_url }}"/>
						<span class="card-title" id="artistName-js" class="pin-header">{{artist_list.0.name}}</span>
					</div>
					<div class="card-content">
						<form action="#" method="POST">
							{% csrf_token %}
							{{ playlist_form.as_p }}
						</form>
						<div class="switch">
							<label>
								Private
								<input id="visibility-js" type="checkbox">
								<span class="lever"></span>
								Public
							</label>
						</div> <br>
						<button id="playlistBtn-js" class="waves-effect waves-light btn" type="submit"><i class="material-icons right">get_app</i>Make Playlist</button>
					</div>
				</div>
			</div>

			<!-- Setlists -->
			<div class="col s6 offset-s6">
				 <ul class="collapsible popout">
					{% for artist in artist_list %}
						<li>
							<div id="result-js" class="setlists-card-js card-panel collapsible-header {% cycle 'teal' 'teal darken-4' %}">
								<h5 class="white-text">
									{{artist.setlist.venue_name}} <br>
									{{artist.setlist.venue_city}}, {{artist.setlist.venue_state}} <br>
									{{artist.setlist.date}}
								</h5>
							</div>

							<div class="collapsible-body white">
								<div class="row">
									<div class="col">
										<h6> Songs </h6>
										<ol id="songsList-js">
											{% if artist.setlist.set_list|length == 0 %}
												<p> There are no songs available for this venue. </p>
											{% else %}
												{% for song in artist.setlist.set_list %}
													{% if not song.name|lower in all_songs %}
														<li class="songName-js red-text">{{ song.name }}</li>
													{% else %}
														<li class="songName-js">{{ song.name }}</li>
													{% endif %}
												{% endfor %}

												{% for song in artist.setlist.encore_list %}
													{% if not song.name|lower in all_songs %}
														<li class="songName-js red-text">{{ song.name }}</li>
													{% else %}
														<li class="songName-js">{{ song.name }}</li>
													{% endif %}
												{% endfor %}
											{% endif %}					
										</ol>
									</div>
									
								</div>
							</div>
						</li>
					{% endfor %}
				</ul> <!-- end accordion -->
			</div> <!-- end col of setlists -->
		</div> <!-- end row -->
	{% endblock %}

	{% block scripts %}
		<script>
			$(document).ready(function() {
				$('.collapsible').collapsible();
				$('.pin-card').pushpin({
					offset: 75
				});
			});
			var songs = '{{all_songs_json}}';
			var all_songs = JSON.stringify(songs)
			all_songs = jQuery.parseJSON(songs.replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&amp;/g,"&"));
		</script>
		<script src="{% static 'play_app/js/searchResult.js' %}"></script>
	{% endblock %}